-- CREACION DE LA TABLA PAISES
CREATE TABLE "Country" (
	"IDCountry" INTEGER NOT NULL,
	"NOC" TEXT NOT NULL,
PRIMARY KEY("IDCountry" AUTOINCREMENT)
);
-- CREACION TABLA CIUDAD
CREATE TABLE "City" (
	"IDCity" INTEGER NOT NULL,
	"City" TEXT NOT NULL,
PRIMARY KEY("IDCity" AUTOINCREMENT)
);
-- CREACION TABLA DE TIPO DE EVENTOS
CREATE TABLE "EventType" (
	"IDPpal" INTEGER NOT NULL,
	"Event" TEXT NOT NULL,
PRIMARY KEY("IDPpal" AUTOINCREMENT)
);
-- CREACION TABLA DEPORTES
CREATE TABLE "Sport" (
	"IDSport" INTEGER NOT NULL,
	"SportName" TEXT NOT NULL,
PRIMARY KEY("IDSport" AUTOINCREMENT)
);
-- CREACION TABLA EQUIPOS
CREATE TABLE "Teams" (
	"IDTeam" INTEGER NOT NULL,
	"Team" TEXT NOT NULL,
PRIMARY KEY("IDTeam" AUTOINCREMENT)
);
-- CREACION TABLA DE MEDALLAS
CREATE TABLE "Medals" (
	"IDMedal" INTEGER NOT NULL,
	"Medal" TEXT,
;PRIMARY KEY("IDMedal" AUTOINCREMENT)
);
-- CREACION DE LA TABLA ATLETAS
CREATE TABLE "Athletes" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Sex"	TEXT,
	"Height"	INTEGER,
	"Weight"	REAL,
	PRIMARY KEY("ID")
);
-- CREACION DE LA TABLA EDICION DEL JUEGO
CREATE TABLE "Games" (
	"IDGame"	INTEGER NOT NULL,
	"Year"	INTEGER NOT NULL,
	"IDCity"	INTEGER NOT NULL,
	"Game"	INTEGER NOT NULL,
	"Season"	INTEGER NOT NULL,
	FOREIGN KEY("IDCity") REFERENCES "City"("IDCity"),
	PRIMARY KEY("IDGame" AUTOINCREMENT)
);
-- CREACION DE TABLA ATLETAS POR EQUIPOS
CREATE TABLE "Athletes_Teams" (
	"ID"	INTEGER NOT NULL,
	"IDTeam"	INTEGER NOT NULL,
	FOREIGN KEY("IDTeam") REFERENCES "Teams"("IDTeam"),
	FOREIGN KEY("ID") REFERENCES "Athletes"("ID")
);
-- CREACION DE TABLA RELACION EVENTOS Y EDICION DEL JUEGO
CREATE TABLE "EventType_Games" (
	"IDGame"	INTEGER NOT NULL,
	"IDPpal"	INTEGER NOT NULL,
	FOREIGN KEY("IDGame") REFERENCES "Games"("IDGame")
);
-- CREACION DE LA TABLA RELACION EJECUCION DE EVENTOS
CREATE TABLE "Events" (
	"ID"	INTEGER NOT NULL,
	"IDPPal"	INTEGER NOT NULL,
	"IDMedal"	INTEGER NOT NULL,
	"IDCountry"	INTEGER NOT NULL,
	"IDTeams"	INTEGER NOT NULL,
	"IDGame"	INTEGER NOT NULL,
	"Age"	INTEGER,
	FOREIGN KEY("IDCountry") REFERENCES "Country"("IDCountry"),
	FOREIGN KEY("IDMedal") REFERENCES "EventType"("IDPpal"),
	FOREIGN KEY("IDPPal") REFERENCES "Athletes"("ID"),
	FOREIGN KEY("IDTeams") REFERENCES "Teams"("IDTeam"),
	FOREIGN KEY("IDGame") REFERENCES "Games"("IDGame")
);